name: "🐙 Check: Source code changes"
description: "Checks for source code changes between commits."

inputs:
  head-ref:
    description: "The tree-like git object which will be compared against 'base-ref'."
    required: false
    default: "${{ github.ref }}"
  base-ref:
    description: "The tree-like git object which 'head-ref' will be compared against."
    required: false
    default: "${{ github.event_name == 'pull_request' && github.base_ref || format('{0}~1', github.ref) }}"
  include:
    description: "A file or directory to restrict changed files to (may be a glob expression)."
    required: false
    default: "**"
  exclude:
    description: "A file or directory to exclude from results (may be a glob expression)."
    required: false

outputs:
  changed:
    description: "Whether any files changed."
    value: ${{ steps.diff-tree.outputs.changed }}

runs:
  using: "composite"
  steps:
    - name: Determine candidate files
      id: files
      shell: bash
      run: |-
        PY_SCRIPT=$(
        cat <<-EOM
        from glob import glob
        included=set(glob("${{ inputs.include }}",recursive=True,include_hidden=True))
        excluded=set(glob("${{ inputs.exclude }}",recursive=True,include_hidden=True))
        print(" ".join(sorted(included-excluded)))
        EOM
        )

        echo "include=$(python3 -c "$PY_SCRIPT")" >> "$GITHUB_OUTPUT"

    - name: Inspect candidate files
      shell: bash
      run: |-
        echo "Candidate files:"
        for f in ${{ steps.files.outputs.include }}; do
          echo "$f"
        done

    - name: Evaluate changed files
      id: diff-tree
      shell: bash
      run: |-
        CHANGED=$(git diff-tree ${{ inputs.head-ref }} ${{ inputs.base-ref }} ${{ steps.files.outputs.include }})

        echo "files=$CHANGED" >> "$GITHUB_OUTPUT"
        echo "changed=$([[ ! -z "$CHANGED" ]] && echo true)" >> "$GITHUB_OUTPUT"

    - name: Inspect changed files
      shell: bash
      run: |-
        echo "Changed: ${{ steps.diff-tree.outputs.changed }}"

        echo "\n"
        echo "Changed files:"
        echo "${{ steps.diff-tree.outputs.files }}"
