name: "ðŸ—ï¸ godot-infra: Install 'podman'-related executables"
description: "Install the 'podman'-related tools."

# NOTE: See https://podman.io/getting-started/installation.

inputs:
  install-buildah:
    description: "Whether to install the latest version of 'buildah'."
    required: false
    default: false
  install-podman:
    description: "Whether to install the latest version of 'podman'."
    required: false
    default: true
  login:
    description: "Whether to log in to the 'ghcr.io/coffeebeats' registry."
    required: false
    default: true

runs:
  using: "composite"
  steps:
    # Update packages to support nice container file features; see
    # https://podman.io/getting-started/installation for context.
    - name: Update tools to latest
      if: inputs.install-buildah == 'true' || inputs.install-podman == 'true'
      shell: bash
      run: |
        sudo mkdir -p /etc/apt/keyrings

        curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/Release.key \
          | gpg --dearmor \
          | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
            https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/ /" \
          | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null

        sudo apt-get update -y

        if [[ "${{ inputs.install-buildah }}" == "true" ]]; then
          sudo apt-get -y install buildah
        fi

        if [[ "${{ inputs.install-podman }}" == "true" ]]; then
          sudo apt-get -y install podman
        fi

    - name: Log in to ghcr.io
      if: inputs.login == 'true'
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
