[config]
  # Inherit from the specified manifest file, merging the configuration in
  # this file on top of the settings in the specified file. 
  extends = "gdbuild.ci.toml"

[godot]
  # The version of Godot to use for compiling and exporting.
  version_file = ".godot-version"

[target.client]
  runnable = true

  pack_files = [
    {glob = ["**/*.gd", "**/*.tscn", "**/*.import"], embed = true, encrypt = true},
    {glob = ["**/*.svg"], embed = true},
  ]

[target.client.profile.release]
  # NOTE: Set the encryption key via the 'SCRIPT_AES256_ENCRYPTION_KEY' variable.
  encrypt = true

[template]
  # A path to a 'custom.py' file which defines export template build options.
  custom_py_path = "custom.py"
