[config]
  # Inherit from the specified manifest file, merging the configuration in
  # this file on top of the settings in the specified file. 
  extends = "gdbuild.ci.toml"

[godot]
  # The version of Godot to use for compiling and exporting.
  version_file = ".godot-version"

[target.client]
  runnable = true

  pack_files = [
    {glob = ["**/*.gd", "**/*.tscn", "**/*.import"], embed = true, encrypt = true},
    {glob = ["**/*.svg"], embed = true},
  ]

[target.client.profile.release]
  # EncryptionKey is the encryption key to embed in the export template.
  encryption_key = "aeb1bc56aaf580cc31784e9c41551e9ed976ecba10d315db591e749f3f64890f"
  encrypt        = true

[template]
  # A path to a 'custom.py' file which defines export template build options.
  custom_py_path = "custom.py"
