name: "ðŸ—ï¸ Compile: Godot export template (Web)"
description: "Compiles a Godot export template for the Web (HTML5) platform."

inputs:
  arch:
    description: "The target architecture to build the export template for."
    required: true
  target:
    description: "Which Godot build target to compile (e.g. 'template_debug')."
    required: true
  encryption-key:
    description: "A Godot script encryption key to embed within the export template."
    required: false
  use-double-precision:
    description: "Whether to enable double precision for the export template."
    required: false
    default: false
  profile:
    description: "The optimization profile of the compiled export template."
    required: false
    default: release
  enable-javascript-eval:
    description: "Whether to expose the JavaScript singleton to the engine."
    required: false
    default: false
  enable-gdextension:
    description: "Whether to enable support for GDExtensions (degrades performance/compatibility)."
    required: false
    default: true
  enable-threads:
    description: "Whether to enable support for WebWorker threads (requires browser support)."
    required: false
    default: true
  godot-src-path:
    description: "A path, relative to 'github.workspace', where the Godot source code is located."
    required: false
    default: "."
  scons-cache-path:
    description: "A path, relative to 'github.workspace', where the SCons cache is located."
    required: false
    default: ".scons"

runs:
  using: docker
  image: docker://ghcr.io/coffeebeats/compile-godot-export-template:godot-v4.4-web
  args:
    - /bin/bash
    - -c
    - >-
      if [[ ! -z "${{ inputs.encryption-key }}" ]]; then
      SCRIPT_AES256_ENCRYPTION_KEY=${{ inputs.encryption-key }};
      fi

      scons
      -j$(nproc)
      -C ${{ inputs.godot-src-path }}
      cache_path=/github/workspace/${{ inputs.scons-cache-path }}
      verbose=yes warnings=extra werror=yes
      arch=${{ inputs.arch }}
      target=${{ inputs.target }}
      $([[ "${{ inputs.use-double-precision }}" == 'true' ]] && echo "precision=double")
      $([[ "${{ inputs.enable-javascript-eval }}" != 'true' ]] && echo "javascript_eval=no")
      $([[ "${{ inputs.enable-gdextension }}" == 'true' ]] && echo "dlink_enabled=yes")
      $([[ "${{ inputs.enable-threads }}" == 'true' ]] && echo "threads=yes" || echo "threads=no")
      $([[ "${{ inputs.profile }}" == "debug" ]] && echo debug_symbols=yes optimize=debug)
      $([[ "${{ inputs.profile }}" == "release_debug" ]] && production=yes debug_symbols=yes optimize=speed_trace)
      $([[ "${{ inputs.profile }}" == "release" ]] && echo production=yes optimize=speed)

      mv
      ${{ inputs.godot-src-path }}/bin/godot.web.*.zip
      "${{ inputs.godot-src-path }}/bin/web$([[ ${{ inputs.enable-gdextension }} == true ]] && echo _dlink)_$([[ ${{ inputs.profile }} == release ]] && echo release || echo debug).zip"

      rm -rf
      .web_zip
      *.js
      *.wasm
