name: "ðŸ“ Archive: MoltenVK SDK"
description: "Compile and archive the specified version of 'MoltenVK' SDK."

# NOTE: This action compiles 'MoltenVK' from source using specific compilation
# flags that restore compatibility with 'osxcross'.

inputs:
  version:
    description: "The 'MoltenVK' version to archive."
    required: true
  xcode-version:
    description: "The 'Xcode' version to use for building/extracting."
    required: false
  osx-version-min:
    description: "The minimum supported 'macOS' version."
    required: true
  out:
    description: "The filename to write the archive to."
    required: false
    default: moltenvk.tar.gz

outputs:
  name:
    description: "The name of the 'MoltenVK' SDK artifact."
    value: ${{ steps.archive.outputs.name }}
  path:
    description: "The path to the 'MoltenVK' SDK artifact."
    value: ${{ steps.archive.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Verify runner OS
      shell: bash
      run: '[[ "${{ runner.os }}" != "macOS" ]] && exit 1 || :'

    - name: Determine output filename
      id: archive
      shell: bash
      run: |
        OUT="${{ inputs.out }}"
        if [[ "$OUT" != *".tar.gz" ]]; then
          echo "Invalid compression; only 'gz' is supported!"
          exit 1
        fi

        echo "name=$(basename $OUT)" >> "$GITHUB_OUTPUT"
        echo "path=$OUT" >> "$GITHUB_OUTPUT"

    - name: Switch 'Xcode' versions
      if: inputs.xcode-version != ''
      shell: bash
      run: |
        sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode-version }}.app
        xcodebuild -version

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        repository: "KhronosGroup/MoltenVK"
        ref: "v${{ inputs.version }}"
        path: "MoltenVK"

    - name: Install 'tree' for inspection
      shell: bash
      run: "brew install tree"

    # See https://github.com/KhronosGroup/MoltenVK#building-moltenvk
    - name: Compile static 'MoltenVK' library
      shell: bash
      working-directory: MoltenVK
      run: |
        ./fetchDependencies --macos

        # FIXME: https://github.com/godotengine/godot/issues/68512
        MACOSX_DEPLOYMENT_TARGET=${{ inputs.osx-version-min }} \
        OTHER_CFLAGS='-fno-objc-msgsend-selector-stubs' \
        make macos

        echo "Inspecting compiled artifacts ('Package/Release/'):"
        tree Package/Release/

    - name: Package library artifact
      shell: bash
      env:
        # Extract the only required library; see
        # https://github.com/godotengine/godot/blob/4.5-stable/platform_methods.py#L138-L161.
        TARGET_DIR: macOS/lib/MoltenVK.xcframework
      run: |
        PACKAGE_DIR="${{ runner.temp }}/dist"

        mkdir -p "$PACKAGE_DIR/$TARGET_DIR"

        mv \
          MoltenVK/Package/Release/MoltenVK/static/MoltenVK.xcframework/macos-* \
          "$PACKAGE_DIR/$TARGET_DIR"

        echo "Inspecting upload artifact, pre-archive:"
        tree "$PACKAGE_DIR"

        find "$PACKAGE_DIR" \
        -type f \
        -o -type l \
        -o -type d | \
        tail -n +2 | \
        sed "s,^$PACKAGE_DIR/,," | \
        tar \
        -czf ${{ steps.archive.outputs.path }} \
        --no-recursion \
        -C $PACKAGE_DIR/ \
        -T -

        echo "Inspecting upload artifact, post-archive:"
        ls ${{ steps.archive.outputs.path }}
