name: "🎮 Publish: itch.io"
description: "Publishes a game project to itch.io."

inputs:
  path:
    description: "The path to the directory containing the project files."
    required: true
  version:
    description: "The version of the game project."
    required: true
  itch-project:
    description: "The name of the 'itch.io' project (e.g. 'user/game')."
    required: true
  itch-channel:
    description: "The name of the 'itch.io' project channel (e.g. 'windows-stable')."
    required: true
  api-key:
    description: "The API key used to authenticate with itch.io."
    required: true

runs:
  using: "composite"
  steps:
    - uses: coffeebeats/godot-infra/.github/actions/setup-butler@main

    - name: Log in to itch.io
      shell: bash
      env:
        BUTLER_API_KEY: ${{ inputs.api-key }}
      run: butler login

    - name: Publish game executable to 'itch.io'
      shell: bash
      run: butler push \
        --if-changed ${{ inputs.path }} \
        --userversion ${{ inputs.version }} \
        ${{ inputs.project }}:${{ inputs.itch-channel }}
