name: "🎮 Publish: itch.io"
description: "Publishes a game project to itch.io."

inputs:
  path:
    description: "The path to the directory containing the project files."
    required: true
  version:
    description: "The version of the game project."
    required: true
  itchio-project:
    description: "The name of the 'itch.io' project (e.g. 'user/game')."
    required: true
  itchio-channel:
    description: "The name of the 'itch.io' project channel (e.g. 'windows-stable')."
    required: true
  api-key:
    description: "The API key used to authenticate with itch.io."
    required: true

runs:
  using: "composite"
  steps:
    - uses: coffeebeats/godot-infra/.github/actions/setup-butler@main

    - name: Log in to itch.io
      shell: bash
      env:
        BUTLER_API_KEY: ${{ inputs.api-key }}
      run: butler login

    - name: Publish game executable to 'itch.io'
      shell: bash
      env:
        BUTLER_API_KEY: ${{ inputs.api-key }}
      run: >-
        butler push
        --if-changed
        --userversion=${{ inputs.version }}
        ${{ inputs.path }}
        ${{ inputs.itchio-project }}:${{ inputs.itchio-channel }}
