name: "🏗️ godot-infra: Build MacOS export template"
description: "Builds a Godot export template for MacOS."

inputs:
  arch:
    description: "The target architecture to build the export template for."
    required: true
  encryption-key:
    description: "A Godot script encryption key to embed within the export template."
    required: false
  profile:
    description: "The optimization profile of the compiled export template."
    required: false
    default: release
  use-double-precision:
    description: "Whether to enable double precision for the export template."
    required: false
    default: false

runs:
  using: "docker"
  image: ghcr.io/coffeebeats/compile-godot-export-template:godot-v4.2-macos
  env:
    SCONS_CACHE: /github/workspace/.scons
    SCRIPT_AES256_ENCRYPTION_KEY: ${{ inputs.encryption-key }}
  args:
    - /bin/bash
    - -c
    - >
      scons

      -j$(nproc)
      -C $GITHUB_WORKSPACE

      platform=macos
      arch=${{ inputs.arch }}

      verbose=yes
      warnings=extra
      werror=yes

      $([[ "${{ inputs.use-double-precision }}" == 'true' ]] && echo "precision=double")

      $([[ "${{ inputs.profile }}" == "debug" ]] && echo target=template_debug dev_mode=yes debug_symbols=yes optimize=debug)
      $([[ "${{ inputs.profile }}" == "release_debug" ]] && echo target=template_debug dev_mode=yes debug_symbols=yes lto=full optimize=speed_trace)
      $([[ "${{ inputs.profile }}" == "release" ]] && echo target=template_release production=yes lto=full optimize=speed)
