name: "🏗️ godot-infra: Build MacOS export template"
description: "Builds a Godot export template for MacOS."

inputs:
  custompy-path:
    description: "A path to a 'custom.py' file containing template build options."
    required: false
  encryption-key:
    description: "A Godot script encryption key to embed within the export template."
    required: false
  profile:
    description: "The optimization profile of the compiled export template."
    required: false
    default: release
  use-double-precision:
    description: "Whether to enable double precision for the export template."
    required: false
    default: false

  # MacOS-specific inputs.
  # ...

  token:
    description: "The token used to authenticate with ghcr.io."
    required: false
    default: "${{ github.token }}"

runs:
  using: docker
  image: "docker://ghcr.io/coffeebeats/compile-godot-export-template:macos-v0.1.0" # x-release-please-version
  entrypoint: entrypoint.sh
  env:
    CUSTOMPY_PATH: ${{ inputs.custompy-path }}
    DOUBLE_PRECISION: ${{ inputs.use-double-precision }}
    PROFILE: ${{ inputs.profile }}

    # Godot-specific environment variables.
    SCONS_CACHE: ${{ github.workspace }}/.scons
    SCONS_CACHE_SIZE: "2000"
    SCRIPT_AES256_ENCRYPTION_KEY: ${{ inputs.encryption-key }}
  credentials:
    username: ${{ github.actor }}
    password: ${{ inputs.token }}
