name: "ðŸ™ godot-infra: Set up 'GitHub' hosted runner"
description: "Configures the 'GitHub' hosted runner for use with 'godot-infra'."

runs:
  using: "composite"
  steps:
    # NOTE: The 'godot-infra' image requires >14GB disk space to build, so to
    # enable building in this workflow, free additional disk space on the
    # runner. For more details see
    # https://github.com/actions/runner-images/issues/2606#issuecomment-772683150
    - name: Free additional disk space
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo rm -rf /usr/local/lib/android # Free ~10 GB; removes Android support
        sudo rm -rf /usr/share/dotnet # Free ~20GB; removes .NET support
        sudo rm -rf /usr/local/share/powershell # Free ~1.2GB; removes PowerShell support
        sudo rm -rf /usr/local/share/chromium # Free ~0.5GB; removes Chromium support

        # Free ~1.3GB; removes Java support
        sudo rm -rf $JAVA_HOME_8_X64 $JAVA_HOME_11_X64 $JAVA_HOME_17_X64 $JAVA_HOME_21_X64
