name: "🐙 Setup: GitHub hosted runner"
description: "Configures the 'GitHub' hosted runner for use with 'godot-infra'."

runs:
  using: "composite"
  steps:
    # NOTE: Free additional disk space on the runner. For more details see
    # https://github.com/actions/runner-images/issues/2606#issuecomment-772683150.
    - name: Free additional disk space
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # Languages & runtimes
        sudo rm -rf /usr/local/.ghcup # ~3GB; removes Haskell support
        sudo rm -rf /usr/local/julia* # ~0.5GB; removes Julia support
        sudo rm -rf /usr/local/lib/android # ~10 GB; removes Android support
        sudo rm -rf /usr/share/dotnet # ~20GB; removes .NET support
        sudo rm -rf /usr/share/swift # ~2.5GB; removes Swift support
        sudo rm -rf $JAVA_HOME_8_X64 $JAVA_HOME_11_X64 $JAVA_HOME_17_X64 $JAVA_HOME_21_X64 # ~1.3GB; removes Java support

        # Tools
        sudo rm -rf /opt/hostedtoolcache/CodeQL # ~2GB; removes CodeQL
        sudo rm -rf /usr/local/share/chromium # ~1.5GB; removes Chrome
        sudo rm -rf /usr/local/share/powershell # ~0.8GB; removes PowerShell
