name: "ðŸ—ï¸ godot-infra: Build 'godot' export template"
description: "Compiles a 'godot' export template."

inputs:
  platform:
    description: "The 'godot' platform to build for."
    required: true
  project-dir:
    description: "The path to the game project directory."
    required: false
    default: "."
  manifest-name:
    description: "The name of the 'gdbuild' manifest (relative to 'project-dir')."
    required: false
    default: "gdbuild.toml"

outputs:
  artifacts:
    description: "The directory containing the export template artifacts."
    value: ${{ steps.config.outputs.runner-dist }}

runs:
  using: "composite"
  steps:
    - name: Export the output directory
      id: config
      shell: bash
      run: |
        # Runner paths
        echo "runner-dist=$HOME/.godot-infra" >> "$GITHUB_OUTPUT"
        echo "runner-scons=$HOME/.scons" >> "$GITHUB_OUTPUT"

        # Container paths
        echo "container-workspace=/home/ubuntu/godot-infra" >> "$GITHUB_OUTPUT"

    - name: Check environment requirements
      shell: bash
      run: |
        [[ -z "$GDENV_HOME" || ! -d "$GDENV_HOME" ]] && echo "Missing 'gdenv'; exit 1" || :
        [[ -z "$GDBUILD_HOME" || ! -d "$GDBUILD_HOME" ]] && echo "Missing 'gdbuild'; exit 1" || :

    - name: Set up 'podman'
      uses: ./.github/actions/setup-podman
      with:
        install-buildah: false
        install-podman: true
        login: true

    - name: Cache the 'godot' export template
      id: cache-template
      uses: actions/cache@v4
      with:
        path: ${{ steps.config.outputs.runner-dist }}
        key: template-${{ runner.os }}-${{ inputs.platform }}-${{ hashFiles(format('{0}/.godot-version', inputs.project-dir)) }}-${{ hashFiles(format('{0}/**/*.toml', inputs.project-dir)) }}
        restore-keys: |
          template-${{ runner.os }}-${{ inputs.platform }}-${{ hashFiles(format('{0}/.godot-version', inputs.project-dir)) }}-
          template-${{ runner.os }}-${{ inputs.platform }}-

    - name: Cache the 'SCons' build directory
      id: cache-scons
      uses: actions/cache@v4
      with:
        path: ${{ steps.config.outputs.runner-scons }}
        key: scons-${{ runner.os }}-${{ inputs.platform }}-${{ hashFiles(format('{0}/**/*', inputs.project-dir)) }}
        restore-keys: |
          scons-${{ runner.os }}-${{ inputs.version }}-

    - name: Compile 'godot' export template
      shell: bash
      run: |
        mkdir -p ${{ steps.config.outputs.runner-dist }}
        mkdir -p ${{ steps.config.outputs.runner-scons }}

        WORKSPACE_DIR="${{ steps.config.outputs.container-workspace }}"

        podman run \
          -v ${{ steps.config.outputs.runner-dist }}:$WORKSPACE_DIR/dist:Z \
          -v ${{ steps.config.outputs.runner-scons }}:$WORKSPACE_DIR/.scons:Z \
          -v $(realpath ${{ inputs.project-dir }}):$WORKSPACE_DIR/project:ro,Z \
          $([[ -d "$GDENV_HOME" ]] && echo "-v $(realpath $GDENV_HOME):$WORKSPACE_DIR/.gdenv:Z") \
          $([[ -d "$GDBUILD_HOME" ]] && echo "-v $(realpath $GDBUILD_HOME):$WORKSPACE_DIR/.gdbuild:Z") \
          ghcr.io/${{ github.repository_owner }}/godot-infra:latest \
          gdbuild template \
          --verbose \
          --config $WORKSPACE_DIR/project/${{ inputs.manifest-name }} \
          --out $WORKSPACE_DIR/tmp \
          ${{ inputs.platform }} && \
          mv $WORKSPACE_DIR/tmp/* $WORKSPACE_DIR/dist
