name: "🏗️ godot-infra: Build 'godot' export template"
description: "Compiles a 'godot' export template."

inputs:
  platform:
    description: "The 'godot' platform to build for."
    required: true
  profile:
    description: "The execution profile to build with."
    required: false
    default: release
  features:
    description: "A space-, comma- or new line-separated list of features to enable."
    required: false
    default: ""
  out-dir:
    description: "The directory in which to place the export templates."
    required: false
    default: "dist"
  project-dir:
    description: "The path to the game project directory."
    required: false
    default: "."
  manifest-path:
    description: "A specific 'gdbuild' manifest filename (relative to 'project-dir')."
    required: false

outputs:
  path:
    description: "The directory containing the export template artifacts."
    value: ${{ steps.config.outputs.runner-dist }}

runs:
  using: "composite"
  steps:
    - name: Set up action configuration
      id: config
      shell: bash
      run: |
        # Runner paths
        echo "runner-project=$(realpath ${{ inputs.project-dir }})"  >> "$GITHUB_OUTPUT"
        echo "runner-dist=$(realpath ${{ inputs.out-dir }})" >> "$GITHUB_OUTPUT"
        echo "runner-scons=$HOME/.scons" >> "$GITHUB_OUTPUT"

        # Container paths
        echo "container-workspace=/home/ubuntu/godot-infra" >> "$GITHUB_OUTPUT"

    - name: Build run command
      id: template
      uses: coffeebeats/gdbuild/.github/actions/run-template@main
      with:
        execute: false
        verbose: true
        platform: ${{ inputs.platform }}
        profile: ${{ inputs.profile }}
        features: ${{ inputs.features }}
        out-dir: ${{ steps.config.outputs.runner-dist }}
        project-dir: ${{ steps.config.outputs.runner-project }}
        manifest-path: ${{ inputs.manifest-path }}

    - name: Execute run command for cached template
      if: steps.template.outputs.cache-hit == 'true'
      shell: bash
      run: ${{ steps.template.outputs.command }}

    - name: Configure runner
      if: steps.template.outputs.cache-hit != 'true'
      uses: ./.github/actions/setup-runner

    - name: Cache the 'SCons' build directory
      if: steps.template.outputs.cache-hit != 'true'
      id: cache-scons
      uses: actions/cache@v4
      with:
        path: ${{ steps.config.outputs.runner-scons }}
        key: scons-${{ runner.os }}-${{ inputs.platform }}-${{ inputs.profile }}-${{ steps.template.outputs.hash }}
        restore-keys: |
          scons-${{ runner.os }}-${{ inputs.platform }}-${{ inputs.profile }}-
          scons-${{ runner.os }}-${{ inputs.platform }}-

    - name: Build run command (within 'godot-infra' container)
      id: template-container
      if: steps.template.outputs.cache-hit != 'true'
      uses: coffeebeats/gdbuild/.github/actions/run-template@main
      with:
        execute: false
        verbose: true
        skip-cache: true # Cache already mounted correctly by prior command.
        skip-hash: true # Hash already computed correctly by prior command.
        platform: ${{ inputs.platform }}
        profile: ${{ inputs.profile }}
        features: ${{ inputs.features }}
        out-dir: ${{ steps.config.outputs.container-workspace }}/dist
        project-dir: ${{ steps.config.outputs.container-workspace }}/project
        manifest-path: ${{ inputs.manifest-path }}

    - name: Validate template hashes match
      if: steps.template.outputs.cache-hit != 'true'
      shell: bash
      run: $([[ "${{ steps.template.outputs.hash }}" != "${{ steps.template-container.outputs.hash }}" ]] && exit 1 || :)

    - name: Set up 'podman'
      if: steps.template.outputs.cache-hit != 'true'
      uses: ./.github/actions/setup-podman
      with:
        login: true

    - name: Compile 'godot' export template
      if: steps.template.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ${{ steps.config.outputs.runner-dist }}
        mkdir -p ${{ steps.config.outputs.runner-scons }}

        WORKSPACE_DIR="${{ steps.config.outputs.container-workspace }}"

        podman run \
          --userns keep-id:uid=1000,gid=1000 \
          -v ${{ steps.config.outputs.runner-dist }}:$WORKSPACE_DIR/dist:Z \
          -v ${{ steps.config.outputs.runner-scons }}:$WORKSPACE_DIR/.scons:Z \
          -v ${{ steps.config.outputs.runner-project }}:$WORKSPACE_DIR/project:ro,Z \
          $([[ -d "$GDENV_HOME" ]] && echo "-v $(realpath $GDENV_HOME):$WORKSPACE_DIR/.gdenv:Z") \
          $([[ -d "$GDBUILD_HOME" ]] && echo "-v $(realpath $GDBUILD_HOME):$WORKSPACE_DIR/.gdbuild:Z") \
          -e SCONS_CACHE=$WORKSPACE_DIR/.scons \
          ghcr.io/${{ github.repository_owner }}/godot-infra:latest bash -c \
          "${{ steps.template-container.outputs.command }}"

    - name: Print 'godot' export template info
      shell: bash
      run: ls -ls ${{ steps.config.outputs.runner-dist }}
