name: "ðŸ—ï¸ Compile: Godot export template (MacOS)"
description: "Compiles a Godot export template for the MacOS platform."

inputs:
  arch:
    description: "The target architecture to build the export template for."
    required: true
  encryption-key:
    description: "A Godot script encryption key to embed within the export template."
    required: false
  use-double-precision:
    description: "Whether to enable double precision for the export template."
    required: false
    default: false
  profile:
    description: "The optimization profile of the compiled export template."
    required: false
    default: release
  lipo:
    description: "Whether to use 'lipo' to assemble an export template targeting a 'universal' architecture."
    required: false
    default: false
  app-bundle:
    description: "Whether to create an app bundle for the export template."
    required: false
    default: false
  godot-src-path:
    description: "A path, relative to 'github.workspace', where the Godot source code is located."
    required: false
    default: "."
  scons-cache-path:
    description: "A path, relative to 'github.workspace', where the SCons cache is located."
    required: false
    default: ".scons"

runs:
  using: docker
  image: ubuntu:24.04
  env:
    SCONS_CACHE: /github/workspace/${{ inputs.scons-cache-path }}
    SCRIPT_AES256_ENCRYPTION_KEY: ${{ inputs.encryption-key }}
  args:
    - /bin/bash
    - -c
    # NOTE: Any extra new-lines contained in this string will be executed as the
    # start of a new command.
    - >-
      scons
      -j$(nproc)
      -C $GITHUB_WORKSPACE/${{ inputs.godot-src-path }}
      platform=macos arch=${{ inputs.arch }}
      verbose=yes warnings=extra werror=yes
      $([[ "${{ inputs.use-double-precision }}" == 'true' ]] && echo "precision=double")
      $([[ "${{ inputs.profile }}" == "debug" ]] && echo target=template_debug debug_symbols=yes optimize=debug)
      $([[ "${{ inputs.profile }}" == "release_debug" ]] && echo target=template_debug production=yes debug_symbols=yes optimize=speed_trace)
      $([[ "${{ inputs.profile }}" == "release" ]] && echo target=template_release production=yes optimize=speed)

      $(
        [[ "${{ inputs.lipo }}" == "true" ]] &&
        lipo
        -create bin/godot.macos.*
        -output bin/godot.macos.template_$([[ "${{ inputs.profile }}" == "release" ]] && echo "release" || echo "debug")$([[ "${{ inputs.use-double-precision }}" == 'true' ]] && echo ".double").universal
      )

      $(
        [[ "${{ inputs.app-bundle }}" == "true" ]] &&
        cp -r misc/dist/macos_template.app bin &&
        mkdir -p bin/macos_template.app/Contents/MacOS &&
        TEMPLATE_NAME=godot.macos.template_$([[ "${{ inputs.profile }}" == "release" ]] && echo "release" || echo "debug")$([[ "${{ inputs.use-double-precision }}" == 'true' ]] && echo ".double").$([[ "${{ inputs.lipo }}" == "true" ]] && echo universal || echo ${{ inputs.arch }}) &&
        cp bin/$TEMPLATE_NAME bin/macos_template.app/Contents/MacOS &&
        zip bin/macos.zip bin/macos_template.app
      )
