name: "📦🔧 Package: Addon"
description: "Packages a plugin or compiled gdextension directory and pushes it to a branch."

inputs:
  subfolder:
    description: "The subfolder under 'addons' that the plugin should be placed."
    required: true
  target-branch:
    description: "The name of the branch to push the packaged addon to."
    required: true
  path:
    description: "The path to the addon's root directory."
    required: false
    default: .
  godot-editor-version:
    description: "The godot editor version to use for reimporting."
    required: false
    default: "v4.5.1-stable"
  file-excludes:
    description: "A comma or newline-delimited list of glob patterns to exclude addon files."
    required: false

runs:
  using: "composite"
  steps:
    - name: Identify commit
      id: commit
      shell: bash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - uses: ./.github/actions/setup-godot
      with:
        version: ${{ inputs.godot-editor-version }}

    - name: Construct addon directory
      id: addon
      shell: bash
      run: |
        echo "Current directory: $PWD"

        PACKAGE_DIR="${{ runner.temp }}/addon"
        echo "Constructing addon directory: $PACKAGE_DIR"

        mkdir "$PACKAGE_DIR"

        # Set options to enable more extensive globbing.
        shopt -s extglob
        shopt -s globstar

        if [[ ! -d "addons/${{ inputs.subfolder }}" ]]; then
          echo "Addon not found under 'addons/'; assuming addon is root-level."
          cp -r * "$PACKAGE_DIR"
        else
          echo "Addon found under 'addons/'; moving addon files."

          # Move nested files into the repository root.
          cp +(LICENSE|license)* "$PACKAGE_DIR" 2>/dev/null || :
          cp +(README|readme)* "$PACKAGE_DIR" 2>/dev/null || :
          cp -r addons/${{ inputs.subfolder }}/* "$PACKAGE_DIR" 2>/dev/null || :
        fi

    - name: Prune addon source
      working-directory: ${{ runner.temp }}/addon
      shell: bash
      run: |
        echo "Pruning files from addon directory: ${{ runner.temp }}/addon"

        # Set options to enable more extensive globbing.
        shopt -s extglob
        shopt -s globstar

        # Remove development/project-related files.
        rm -f project.godot
        rm -f icon.*
        rm -rf script_templates

        # Remove all nested addon dependencies.
        rm -rf addons

        # Remove manually specified
        set -f

        for pattern in $(
            set -f
            echo "${{ inputs.file-excludes }}" | tr ',' '\n' | sed -E 's/\\n/ /'
        ); do
            if [[ "$(
                set +f
                realpath -m "${pattern/\~/$HOME}"
            )" != "$PWD"* ]]; then
                echo "Refusing to execute insecure pattern: $pattern"
                exit 1
            fi

            echo "Removing files that match pattern: $pattern"
            (
                set +f
                rm -rf $pattern
            )
        done

        set +f

    - name: Add a '.gitignore' file
      working-directory: ${{ runner.temp }}/addon
      shell: bash
      run: |
        if [[ ! -f ".gitignore" ]]; then
            touch ".gitignore"
        else
          echo "" >> ".gitignore"
        fi

        cat <<EOM >> ".gitignore"
        # DO NOT EDIT: The below entries were generated by 'coffeebeats/godot-infra/package-addon':

        # MacOS-specific ignores
        .DS_Store

        # Windows-specific ignores
        ~*
        *.TMP
        EOM

    # Reimport assets so '*.import' files are updated.
    - name: Reimport assets
      shell: bash
      run: |
        echo "Current directory: $PWD"

        PACKAGE_DIR="${{ runner.temp }}/addon"
        echo "Reimporting assets in addon directory: $PACKAGE_DIR"

        PROJECT_DIR="addons/${{ inputs.subfolder }}"
        echo "Installing into project directory: $PROJECT_DIR"

        if [[ ! -f "project.godot" ]]; then
          CREATED_PROJECT_MANIFEST=1
          touch project.godot
        fi

        # Add packaged directory into project as an addon. This ensures paths
        # within '*.import' files match what a project would require.
        rm -rf "$PROJECT_DIR"
        mv "$PACKAGE_DIR" "$PROJECT_DIR"

        # NOTE: It's okay if this fails, probably. For example, coffeebeats/gut
        # at '24f97b756fcc6a82375ef24b44c84bb1ee781786' fails with Godot
        # 'v4.3-stable', but after the relevant imports occur.
        godot --editor --headless --import --quit || :

        # Move the updated addon folder to the target path.
        mv "$PROJECT_DIR" "$PACKAGE_DIR"

        if [[ $CREATED_PROJECT_MANIFEST -eq 1 ]]; then
          rm project.godot
        fi

    - name: Inspect packaged addon
      working-directory: ${{ runner.temp }}/addon
      shell: bash
      run: "tree -lha --dirsfirst -I .git"

      # Reset the working tree since we don't need to keep edits.
    - name: Restore worktree
      shell: bash
      run: "git restore ."

    - name: Push the latest changes to the target branch
      shell: bash
      run: |
        # Check out to target branch
        BRANCHES=$(git ls-remote --heads origin ${{ inputs.target-branch }})

        if [[ -z "$BRANCHES" ]]; then
          git checkout -b ${{ inputs.target-branch }}
        else
          git fetch origin +refs/heads/${{ inputs.target-branch }}:refs/heads/${{ inputs.target-branch }}
          git checkout ${{ inputs.target-branch }}
        fi

        # Set options to enable more extensive globbing.
        shopt -s extglob
        shopt -s globstar

        rm -rf * .@(!(.||git))

        echo "Target addon workspace (before):"
        tree -lha --dirsfirst -I .git

        cp -r ${{ runner.temp }}/addon/* ${{ runner.temp }}/addon/.gitignore .

        echo "Target addon workspace (after):"
        tree -lha --dirsfirst -I .git

    - uses: ./commit-changes
      with:
        description: "updating \\`${{ inputs.subfolder }}\\` to ${{ steps.commit.outputs.sha_short }}"
        target-branch: ${{ inputs.target-branch }}
