name: "🐙 Check: Check and fix source code formatting"
description: "Check project formatting, and if it fails, fix it."

inputs:
  check-command:
    description: "The command that checks if formatting is correct."
    required: true
  fix-command:
    description: "The command that fixes formatting if incorrect."
    required: true

runs:
  using: "composite"
  steps:
    # Check source code
    - name: Check formatting
      id: check-formatting
      continue-on-error: true
      shell: bash
      run: |-
        # Set options to enable more extensive globbing.
        shopt -s extglob
        shopt -s globstar

        ${{ inputs.check-command }}

    # Fix source code
    - name: Fix formatting
      if: steps.check-formatting.outcome == 'failure'
      shell: bash
      run: |-
        # Set options to enable more extensive globbing.
        shopt -s extglob
        shopt -s globstar

        ${{ inputs.fix-command }}

    - uses: coffeebeats/godot-infra/commit-changes@v2
      if: steps.check-formatting.outcome == 'failure'
      with:
        description: "fix formatting"

    - name: Fail workflow
      if: steps.check-formatting.outcome == 'failure'
      shell: bash
      run: exit 1
