name: "🏗️ godot-infra: Build Windows export template"
description: "Builds a Godot export template for Windows."

inputs:
  arch:
    description: "The target architecture to build the export template for."
    required: false
    default: x86_64
  encryption-key:
    description: "A Godot script encryption key to embed within the export template."
    required: false
  use-double-precision:
    description: "Whether to enable double precision for the export template."
    required: false
    default: false
  profile:
    description: "The optimization profile of the compiled export template."
    required: false
    default: release

runs:
  using: docker
  image: ubuntu:24.04
  env:
    SCONS_CACHE: /github/workspace/.scons
    SCRIPT_AES256_ENCRYPTION_KEY: ${{ inputs.encryption-key }}
  args:
    - echo
    - -j$(nproc)
    - -C $GITHUB_WORKSPACE
    - platform=windows
    - arch=${{ inputs.arch }}
    - verbose=yes
    - warnings=extra
    - werror=yes
    - $([[ "${{ inputs.use-double-precision }}" == 'true' ]] && echo "precision=double")
    - $([[ "${{ inputs.profile }}" == "debug" ]] && echo target=template_debug dev_mode=yes debug_symbols=yes optimize=debug)
    - $([[ "${{ inputs.profile }}" == "release_debug" ]] && echo target=template_debug dev_mode=yes debug_symbols=yes lto=full optimize=speed_trace)
    - $([[ "${{ inputs.profile }}" == "release" ]] && echo target=template_release production=yes lto=full optimize=speed)
