name: "🏗️ godot-infra: Build Windows export template"
description: "Builds a Godot export template for Windows."

inputs:
  encryption-key:
    description: "A Godot script encryption key to embed within the export template."
    required: false
  custompy-path:
    description: "A path to a 'custom.py' file containing template build options."
    required: false
  use-double-precision:
    description: "Whether to enable double precision for the export template."
    required: false
    default: false
  profile:
    description: "The optimization profile of the compiled export template."
    required: false
    default: release

  # Windows-specific inputs.
  icon-path:
    description: "A path to an application icon."
    required: true

  token:
    description: "The token used to authenticate with ghcr.io."
    required: false
    default: "${{ github.token }}"

runs:
  using: docker
  image: "docker://ghcr.io/coffeebeats/compile-godot-export-template:windows-v0.1.0" # x-release-please-version
  entrypoint: entrypoint.sh
  env:
    CUSTOMPY_PATH: ${{ inputs.custompy-path }}
    DOUBLE_PRECISION: ${{ inputs.use-double-precision }}
    ICON_PATH: ${{ inputs.icon-path }}
    PROFILE: ${{ inputs.profile }}

    # Godot-specific environment variables.
    SCONS_CACHE: .scons
    SCRIPT_AES256_ENCRYPTION_KEY: ${{ inputs.encryption-key }}
