name: "🤖 godot-infra: Export 'gdbuild' target"
description: "Exports a 'gdbuild' target."

inputs:
  target:
    description: "The name of the 'gdbuild' target to export."
    required: true
  platform:
    description: "The 'godot' platform to build for."
    required: true
  profile:
    description: "The execution profile to build with."
    required: false
    default: release
  features:
    description: "A space-, comma- or new line-separated list of features to enable."
    required: false
    default: ""
  out-dir:
    description: "The directory in which to place the exported artifacts."
    required: false
    default: "dist"
  project-dir:
    description: "The path to the game project directory."
    required: false
    default: "."
  manifest-path:
    description: "A specific 'gdbuild' manifest filename (relative to 'project-dir')."
    required: false
  template-archive-path:
    description: "A path to a 'gdbuild' template archive."
    required: false

outputs:
  path:
    description: "The directory containing the exported artifacts."
    value: ${{ steps.config.outputs.runner-dist }}

runs:
  using: "composite"
  steps:
    - name: Set up action configuration
      id: config
      shell: bash
      run: |
        # Runner paths
        DIST_DIR="$(realpath ${{ inputs.out-dir }})"
        mkdir -p DIST_DIR

        echo "runner-dist=$DIST_DIR" >> "$GITHUB_OUTPUT"

    - name: Run the hash print command
      id: target-hash
      shell: bash
      run: |
        mkdir -p ${{ steps.config.outputs.runner-dist }}

        FEATURES=()
        for f in $(printf "${{ inputs.features }}" | tr -s ', ' \\n); do
          FEATURES+=(--feature $f)
        done

        HASH=$(
          gdbuild target \
            --print-hash \
            --project ${{ inputs.project-dir }} \
            ${FEATURES[@]} \
            $([[ '${{ inputs.profile }}' == 'debug' ]] && echo '--debug') \
            $([[ '${{ inputs.profile }}' == 'release' ]] && echo '--release') \
            $([[ '${{ inputs.profile }}' == 'release_debug' ]] && echo '--release_debug') \
            $([[ '${{ inputs.template-archive-path }}' != '' ]] && echo --template-archive '${{ inputs.template-archive-path }}') \
            $([[ '${{ inputs.manifest-path }}' != '' ]] && echo --config '${{ inputs.project-dir }}/${{ inputs.manifest-path }}') \
            --platform ${{ inputs.platform }} \
            ${{ inputs.target }}
        )

        echo "value=$(echo $HASH | tail -1)" >> $GITHUB_OUTPUT

    - name: Cache the 'gdbuild' store's target exports directory
      id: store
      uses: actions/cache@v4
      with:
        path: ${{ env.GDBUILD_HOME }}/exports
        key: exports-${{ runner.os }}-${{ steps.target-hash.outputs.value }}

    - name: Run the export command
      shell: bash
      run: |
        FEATURES=()
        for f in $(printf "${{ inputs.features }}" | tr -s ', ' \\n); do
          FEATURES+=(--feature $f)
        done

        gdbuild target \
          --verbose \
          --out ${{ inputs.out-dir }} \
          --project ${{ inputs.project-dir }} \
          ${FEATURES[@]} \
          $([[ '${{ inputs.profile }}' == 'debug' ]] && echo '--debug') \
          $([[ '${{ inputs.profile }}' == 'release' ]] && echo '--release') \
          $([[ '${{ inputs.profile }}' == 'release_debug' ]] && echo '--release_debug') \
          $([[ '${{ inputs.template-archive-path }}' != '' ]] && echo --template-archive '${{ inputs.template-archive-path }}') \
          $([[ '${{ inputs.manifest-path }}' != '' ]] && echo --config '${{ inputs.project-dir }}/${{ inputs.manifest-path }}') \
          --platform ${{ inputs.platform }} \
          ${{ inputs.target }}

    - name: Print exported target artifacts info
      shell: bash
      run: ls -ls ${{ steps.config.outputs.runner-dist }}
