name: "🤖 godot-infra: Export 'gdbuild' target"
description: "Exports a 'gdbuild' target."

inputs:
  target:
    description: "The name of the 'gdbuild' target to export."
    required: true
  platform:
    description: "The 'godot' platform to build for."
    required: true
  profile:
    description: "The execution profile to build with."
    required: false
    default: release
  features:
    description: "A space-, comma- or new line-separated list of features to enable."
    required: false
    default: ""
  out-dir:
    description: "The directory in which to place the exported artifacts."
    required: false
    default: "dist"
  project-dir:
    description: "The path to the game project directory."
    required: false
    default: "."
  manifest-path:
    description: "A specific 'gdbuild' manifest filename (relative to 'project-dir')."
    required: false
  template-archive-path:
    description: "A path to a 'gdbuild' template archive."
    required: false

outputs:
  path:
    description: "The directory containing the exported artifacts."
    value: ${{ steps.config.outputs.runner-dist }}

runs:
  using: "composite"
  steps:
    - name: Configure action properties
      id: config
      shell: bash
      run: |
        # Create required directories
        mkdir -p ${{ inputs.out-dir }}

        # Export runner paths
        echo "runner-project=$(realpath ${{ inputs.project-dir }})"  >> "$GITHUB_OUTPUT"
        echo "runner-dist=$(realpath ${{ inputs.out-dir }})" >> "$GITHUB_OUTPUT"

        # Export container paths
        echo "container-workspace=/home/ubuntu/godot-infra" >> "$GITHUB_ENV"

    - name: Set up 'podman'
      uses: ./.github/actions/setup-podman
      with:
        login: true
        install-buildah: false
        install-podman: true

    # TODO: Centralize this once additional secrets need to be set.
    - name: Create a secret for the encryption key
      if: env.SCRIPT_AES256_ENCRYPTION_KEY != ''
      shell: bash
      run: podman secret create --env=true encryption-key SCRIPT_AES256_ENCRYPTION_KEY

    - name: Run the hash print command
      id: target-hash
      shell: bash
      run: |
        FEATURES=()
        for f in $(printf "${{ inputs.features }}" | tr -s ', ' \\n); do
          FEATURES+=(--feature $f)
        done

        HASH=$(
          podman run \
            --userns keep-id:uid=1000,gid=1000 \
            -v ${{ steps.config.outputs.runner-project }}:${{ env.container-workspace }}/project:ro,Z \
            $([[ '${{ inputs.template-archive-path }}' != '' ]] && echo "-v $(realpath ${{ inputs.template-archive-path }}):${{ env.container-workspace }}/template-archive.tar.gz") \
            $([[ -d "$GDENV_HOME" ]] && echo "-v $(realpath $GDENV_HOME):${{ env.container-workspace }}/.gdenv:Z") \
            $([[ -d "$GDPACK_HOME" ]] && echo "-v $(realpath $GDPACK_HOME):${{ env.container-workspace }}/.gdpack:Z") \
            $([[ -d "$GDBUILD_HOME" ]] && echo "-v $(realpath $GDBUILD_HOME):${{ env.container-workspace }}/.gdbuild:Z") \
            --secret encryption-key,type=env,target=SCRIPT_AES256_ENCRYPTION_KEY \
            ghcr.io/${{ github.repository_owner }}/godot-infra:latest gdbuild target \
              --print-hash \
              --project ${{ env.container-workspace }}/project \
              ${FEATURES[@]} \
              $([[ '${{ inputs.profile }}' == 'debug' ]] && echo --debug) \
              $([[ '${{ inputs.profile }}' == 'release' ]] && echo --release) \
              $([[ '${{ inputs.profile }}' == 'release_debug' ]] && echo --release_debug) \
              $([[ '${{ inputs.template-archive-path }}' != '' ]] && echo --template-archive "${{ env.container-workspace }}/template-archive.tar.gz") \
              $([[ '${{ inputs.manifest-path }}' != '' ]] && echo --config "${{ env.container-workspace }}/project/${{ inputs.manifest-path }}") \
              --platform ${{ inputs.platform }} \
              ${{ inputs.target }}
        )

        echo "value=$(echo $HASH | tail -1)" >> $GITHUB_OUTPUT

    - name: Cache the 'gdbuild' store's target exports directory
      id: store
      uses: actions/cache@v4
      with:
        path: ${{ env.GDBUILD_HOME }}/exports
        key: exports-${{ runner.os }}-${{ steps.target-hash.outputs.value }}

    - name: Run the export command
      shell: bash
      run: |
        FEATURES=()
        for f in $(printf "${{ inputs.features }}" | tr -s ', ' \\n); do
          FEATURES+=(--feature $f)
        done

        HASH=$(
          podman run \
            --userns keep-id:uid=1000,gid=1000 \
            -v ${{ steps.config.outputs.runner-project }}:${{ env.container-workspace }}/project:Z \
            $([[ '${{ inputs.template-archive-path }}' != '' ]] && echo "-v $(realpath ${{ inputs.template-archive-path }}):${{ env.container-workspace }}/$(basename ${{ inputs.template-archive-path }})") \
            $([[ -d "$GDENV_HOME" ]] && echo "-v $(realpath $GDENV_HOME):${{ env.container-workspace }}/.gdenv:Z") \
            $([[ -d "$GDPACK_HOME" ]] && echo "-v $(realpath $GDPACK_HOME):${{ env.container-workspace }}/.gdpack:Z") \
            $([[ -d "$GDBUILD_HOME" ]] && echo "-v $(realpath $GDBUILD_HOME):${{ env.container-workspace }}/.gdbuild:Z") \
            --secret encryption-key,type=env,target=SCRIPT_AES256_ENCRYPTION_KEY \
            ghcr.io/${{ github.repository_owner }}/godot-infra:latest gdbuild target \
              --verbose \
              --out ${{ env.container-workspace }}/dist \
              --project ${{ env.container-workspace }}/project \
              ${FEATURES[@]} \
              $([[ '${{ inputs.profile }}' == 'debug' ]] && echo --debug) \
              $([[ '${{ inputs.profile }}' == 'release' ]] && echo --release) \
              $([[ '${{ inputs.profile }}' == 'release_debug' ]] && echo --release_debug) \
              $([[ '${{ inputs.template-archive-path }}' != '' ]] && echo --template-archive "${{ env.container-workspace }}/$(basename ${{ inputs.template-archive-path }}") \
              $([[ '${{ inputs.manifest-path }}' != '' ]] && echo --config "${{ env.container-workspace }}/project/${{ inputs.manifest-path }}") \
              --platform ${{ inputs.platform }} \
              ${{ inputs.target }}
        )

    - name: Print exported target artifacts info
      shell: bash
      run: ls -ls ${{ steps.config.outputs.runner-dist }}
