name: "🤖 Export: Godot project export preset (Windows)"
description: "Exports a Godot project export preset for the Windows platform."

inputs:
  preset-name:
    description: "The name of the Godot project export preset."
    required: true
  preset-output-path:
    description: "A path, relative to 'github.workspace', where the exported Godot preset will be output."
    required: true
  verbose:
    description: "Whether to enable verbose logging when exporting the preset."
    required: false
    default: false

  project-path:
    description: "A path, relative to 'github.workspace', where the Godot project is located."
    required: false
    default: "."
  godot-editor-path:
    description: "A path, relative to 'github.workspace', where the Godot editor executable is located."
    required: true

  pck-only:
    description: "Whether to export a PCK file instead of an executable."
    required: true
  profile:
    description: "The optimization profile of the exported project preset."
    required: false
    default: release
  encryption-key:
    description: "A Godot script encryption key to encrypt exported resources with."
    required: false

  # See https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_windows.html.
  codesign-identity-type:
    required: false
  codesign-identity:
    required: false
  codesign-password:
    required: false

runs:
  using: docker
  image: docker://ghcr.io/coffeebeats/export-godot-project-preset:godot-v4.3-windows
  env:
    GODOT_SCRIPT_ENCRYPTION_KEY: ${{ inputs.encryption-key }}
    GODOT_WINDOWS_CODESIGN_IDENTITY_TYPE: ${{ inputs.codesign-identity-type }}
    GODOT_WINDOWS_CODESIGN_IDENTITY: ${{ inputs.codesign-identity }}
    GODOT_WINDOWS_CODESIGN_PASSWORD: ${{ inputs.codesign-password }}
  args:
    - /bin/bash
    - -c
    - >-
      $GITHUB_WORKSPACE/${{ inputs.godot-editor-path }}
      --path $GITHUB_WORKSPACE/${{ inputs.project-path }}
      --headless
      $([[ ${{ inputs.verbose }} == true ]] && echo --verbose)
      $([[ ${{ inputs.profile }} == debug && ${{ inputs.pck-only }} != true ]] && echo --export-debug)
      $([[ ${{ inputs.profile }} == release_debug && ${{ inputs.pck-only }} != true ]] && echo --export-debug)
      $([[ ${{ inputs.profile }} == release && ${{ inputs.pck-only }} != true ]] && echo --export-release)
      $([[ ${{ inputs.pck-only }} == true ]] && echo --export-pack)
      '${{ inputs.preset-name }}'
      $GITHUB_WORKSPACE/${{ inputs.preset-output-path }}
