name: "ðŸ™ Commit: Source code changes"
description: "Commits and pushes source code changes."

inputs:
  path-expression:
    description: "Path expression to stage."
    required: false
    default: "."
  description:
    description: "The commit message body to write (will be set as a 'chore:' conventional commit)."
    required: false
    default: "commit changes"
  push:
    description: "Whether to push the staged changes."
    required: false
    default: true
  target-branch:
    description: "The name of the remote branch to push to (only used if 'push' is 'true')."
    required: false

runs:
  using: "composite"
  steps:
    - name: Evaluate target branch
      id: target-branch
      shell: bash
      run: |-
        TARGET_BRANCH=$([[ ! -z "${{ inputs.target-branch }}" ]] && echo "${{ inputs.target-branch }}" || git branch --show-current)
        REMOTE_BRANCHES="$(git ls-remote --heads origin $TARGET_BRANCH)"

        echo "name=$TARGET_BRANCH" >> $GITHUB_OUTPUT
        echo "exists=$([[ ! -z "$REMOTE_BRANCHES" ]] && echo true || echo false)" >> $GITHUB_OUTPUT

    - name: Evaluate change set
      id: changeset
      shell: bash
      run: echo empty=$([[ "$(git status --porcelain)" == "" ]] && echo true || echo false) >> $GITHUB_OUTPUT

    - name: Commit changes
      if: steps.changeset.outputs.empty == 'false'
      shell: bash
      run: |-
        git status 

        # See https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        git add --all ${{ inputs.path-expression }}
        git commit -m "chore: ${{ inputs.description }} (on behalf of '${{ github.triggering_actor }}')"

    - name: Push changes
      if: |
        inputs.push == 'true' &&
        (
          steps.changeset.outputs.empty == 'false' ||
          steps.target-branch.outputs.exists == 'false'
        )
      shell: bash
      run: git push origin "${{ steps.target-branch.outputs.name }}"
