name: "✅ Check: Check Godot project source code"
description: "Formats and lints source code for a Godot project."

inputs:
  path:
    description: "Path to the Godot project."
    required: false
    default: "."
  ignore-lint-errors:
    description: "Whether to ignore 'gdlint' errors."
    required: false
    default: false
  line-length-max:
    description: "The maximum allow line length for '.gd' files."
    required: false
    default: 88

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        cache: pip

    - name: Set up 'gdtoolkit'
      shell: bash
      run: pip install "gdtoolkit==4.*"

    - uses: ./.github/actions/check-code-formatting
      with:
        check-command: "gdformat -l ${{ inputs.line-length-max }} --check ${{ inputs.path }}/**/*.gd"
        fix-command: "gdformat -l ${{ inputs.line-length-max }} ${{ inputs.path }}/**/*.gd"

    - name: Lint project
      shell: bash
      continue-on-error: ${{ fromJson(inputs.ignore-lint-errors) }}
      run: |
        # Set options to enable more extensive globbing.
        shopt -s extglob
        shopt -s globstar

        gdlint ${{ inputs.path }}/**/*.gd
