name: "ðŸ“ Archive: MacOS SDK"

inputs:
  version:
    description: "The macOS SDK version to build with."
    required: true
  xcode-version:
    description: "The 'Xcode' version to use for building/extracting."
    required: true
  dir:
    description: "The directory to write the archive to."
    required: false
    default: "."

outputs:
  name:
    description: "The name of the 'macOS' SDK artifact."
    value: ${{ steps.archive.outputs.name }}
  dir:
    description: "The containing directory of the 'macOS' SDK artifact."
    value: ${{ inputs.dir }}

runs:
  using: "composite"
  steps:
    - name: Verify runner OS
      shell: bash
      run: '[[ "${{ runner.os }}" != "macOS" ]] && exit 1 || :'

    - name: Determine output filename
      id: archive
      shell: bash
      run: echo "name=MacOSX${{ inputs.version }}.sdk.tar.gz" >> "$GITHUB_OUTPUT"

    - name: Create macOS SDK archive
      shell: bash
      run: |
        XCODEDIR=/Applications/Xcode_${{ inputs.xcode-version }}.app

        # NOTE(#468): Remove redefined 'libxml2' module prior to packaging SDK.
        rm -f $XCODEDIR/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2/libxml

        SDK_VERSION=${{ inputs.version }} \
        SDK_COMPRESSOR=gz \
        XCODEDIR=$XCODEDIR \
          thirdparty/osxcross/tools/gen_sdk_package.sh

        echo "Files in current directory:"
        ls -l

        mkdir -p ${{ inputs.dir }}

        # Only move the file if necessary.
        if [[ ! -f "${{ inputs.dir }}/${{ steps.archive.outputs.name }}" ]]; then
          mv ${{ steps.archive.outputs.name }} ${{ inputs.dir }}
        fi
