name: "🤖 Install: Download Godot source code"
description: "Downloads the Godot source code and vendors it to a directory and/or artifact."

inputs:
  godot-src-rev:
    type: string
    description: "The revision/tag name in the 'godot-src-repository' to check out."
    required: true
  godot-src-repository:
    type: string
    description: "The name of a GitHub repository containing the Godot source code."
    required: false
    default: godotengine/godot

  dst-path:
    type: string
    description: "A destination path to vendor the Godot source code into (skipped if empty)."
    required: false
    default: ""
  artifact-name:
    type: string
    description: "An artifact name to upload the source code under (skipped if empty)."
    required: false
    default: ""

outputs:
  major-minor-version:
    description: "The major-minor version of the source code."
    value: ${{ steps.godot.outputs.major-minor }}
  semantic-version:
    description: "The full semantic version of the source code."
    value: ${{ steps.godot.outputs.semantic }}

runs:
  using: "composite"
  steps:
    - name: Clone the Godot source code
      shell: bash
      run: >-
        GH_TOKEN=${{ github.token }}
        gh repo clone
        ${{ inputs.godot-src-repository }}
        ${{ github.workspace }}/godot-${{ inputs.godot-src-rev }}
        --
        -b ${{ inputs.godot-src-rev }}
        --depth 1
        --no-tags

        rm -rf ${{ github.workspace }}/godot-${{ inputs.godot-src-rev }}/.git

    - name: Determine the Godot version
      id: godot
      uses: "coffeebeats/godot-infra/.github/actions/parse-godot-version@main"
      with:
        versionpy-path: ${{ github.workspace }}/godot-${{ inputs.godot-src-rev }}/version.py

    - name: Verify source code checkout
      shell: bash
      run: "[[ ! -f '${{ github.workspace }}/godot-${{ inputs.godot-src-rev }}/version.py' ]] && exit 1 || :"

    - name: Upload the source code artifact
      if: inputs.artifact-name != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ github.workspace }}/godot-${{ inputs.godot-src-rev }}
        if-no-files-found: error

    - name: Copy the source code to 'dst-path'
      if: inputs.dst-path != ''
      shell: bash
      run: |
        if [[ "$(realpath ${{ inputs.dst-path }})" == "$(realpath ${{ github.workspace }}/godot-${{ inputs.godot-src-rev }})" ]]; then
          echo "Godot source code already at target directory; exiting without making changes."
          exit 0
        fi

        mv ${{ github.workspace }}/godot-${{ inputs.godot-src-rev }} ${{ inputs.dst-path }}
        echo "Moved Godot source code to target directory: $(realpath ${{ inputs.dst-path }})"
