name: "ðŸ—ï¸ Compile: Godot export template"
description: "Compiles a Godot export template for the specified platform."

inputs:
  godot-src-rev:
    type: string
    description: "The revision/tag name in the 'godot-src-repository' to check out."
    required: true
  godot-src-repository:
    type: string
    description: "The name of a repository containing the Godot source code."
    required: false
    default: godotengine/godot

  arch:
    description: "The target architecture of the export template."
    required: true
  platform:
    description: "The target platform of the export template."
    required: true

  encryption-key:
    description: "A Godot script encryption key to embed within the export template."
    required: false
  custompy-path:
    description: "A path to a 'custom.py' file containing template build options."
    required: false
  use-double-precision:
    description: "Whether to enable double precision for the export template."
    required: false
    default: false
  profile:
    description: "The optimization profile of the compiled export template."
    required: false
    default: release

  # MacOS-specific inputs.
  # ...

  # Web-specific inputs.
  enable-javascript-eval:
    description: "Whether to expose the JavaScript singleton to the engine."
    required: false
    default: false
  enable-gdextension:
    description: "Whether to enable support for GDExtensions (degrades performance/compatibility)."
    required: false
    default: false

  # Windows-specific inputs.
  icon-path:
    description: "A path to an application icon (only used on Windows)."
    required: false

  publish:
    description: "Whether to publish an artifact to the workflow."
    required: false
    default: false
  artifact-name:
    description: "The uploaded artifact's name (only used if 'publish' is 'true')."
    required: false

outputs:
  path:
    description: "The path to the compiled export template artifact."
    value: ${{ steps.artifact.outputs.path }}

runs:
  using: composite

  steps:
    # --------------------- Vendor the Godot source code --------------------- #

    - uses: coffeebeats/godot-infra/.github/actions/install-godot-source@main
      id: godot
      with:
        dst-path: ${{ github.workspace }}/godot
        godot-src-rev: ${{ inputs.godot-src-rev }}
        godot-src-repository: ${{ inputs.godot-src-repository }}

    - name: Parse Godot source code version
      uses: "coffeebeats/godot-infra/.github/actions/parse-godot-version@main"
      id: godot-version
      with:
        versionpy-path: ${{ github.workspace }}/godot/version.py
        minimum-major-version: 4
        minimum-minor-version: 3
        minimum-patch-version: 0

    # -------------- Restore the export template + SCons caches -------------- #

    # NOTE: This is required so as to avoid leaking the encryption key.
    - name: Determine Godot export template cache ID
      id: export-template-cache-id
      shell: bash
      run: |
        INPUT="${{ inputs.platform }}-${{ inputs.arch }}-${{ hashFiles(format('{0}/godot', github.workspace)) }}"
        INPUT="$INPUT-${{ inputs.profile }}-${{ inputs.encryption-key }}-${{ inputs.use-double-precision }}"
        INPUT="$INPUT-${{ hashFiles(inputs.custompy-path) }}-${{ hashFiles(inputs.icon-path) }}"

        echo "value=$(echo "$INPUT" | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

    - name: Validate build directories don't exist
      shell: bash
      run: |
        if [[ -d "${{ github.workspace }}/build" ]]; then
          echo "Unexpectedly found build directory."
          exit 1
        fi

        if [[ -d "${{ github.workspace }}/.scons" ]]; then
          echo "Unexpectedly found SCons cache directory."
          exit 1
        fi

    - name: Cache the Godot export template
      id: export-template
      uses: actions/cache@v4
      with:
        # NOTE: This path must match the one expected by the container action.
        # IF/ELSE: Update the 'save' step below if this changes.
        path: ${{ github.workspace }}/build
        key: export-template-${{ runner.os }}-${{ steps.export-template-cache-id.outputs.value }}

    - name: Inspect restored artifacts
      if: steps.export-template.outputs.cache-hit == 'true'
      shell: bash
      run: tree -lha --dirsfirst $GITHUB_WORKSPACE/build

    - name: Cache the 'SCons' build directory
      if: steps.export-template.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        # NOTE: This path must match the one expected by the container action.
        path: ${{ github.workspace }}/.scons
        key: scons-${{ runner.os }}-${{ inputs.platform }}-${{ inputs.arch }}-${{ inputs.profile }}-${{ inputs.use-double-precision }}-${{ hashFiles(inputs.godot-src-path) }}-${{ hashFiles(inputs.custompy-path) }}
        restore-keys: |
          scons-${{ runner.os }}-${{ inputs.platform }}-${{ inputs.arch }}-${{ inputs.profile }}-${{ inputs.use-double-precision }}-${{ hashFiles(inputs.godot-src-path) }}-

    # ------------------------ Set up build workspace ------------------------ #

    - name: Clear output directory
      if: steps.export-template.outputs.cache-hit != 'true'
      shell: bash
      run: rm -rf $GITHUB_WORKSPACE/godot/bin

    - name: Copy 'custom.py' into Godot source code directory
      if: |
        inputs.custompy-path != '' &&
        steps.export-template.outputs.cache-hit != 'true'
      shell: bash
      run: cp ${{ inputs.custompy-path }} ${{ github.workspace }}/godot/custom.py

    - name: Copy icon into Godot source code directory
      if: |
        inputs.icon-path != '' &&
        inputs.platform == 'windows' &&
        steps.export-template.outputs.cache-hit != 'true'
      shell: bash
      run: |
        ICON_PATH="${{ inputs.icon-path }}"
        if [[ "${{ endsWith(inputs.icon-path, '.ico') }}" != "true" ]]; then
          # NOTE: As of ubuntu-22.04, GitHub runner images don't contain ImageMagick
          # by default [1]. Install that prior to creating the icon.
          #
          # [1] https://github.com/actions/runner-images/issues/10772
          sudo apt-get update -y
          sudo apt-get install -y imagemagick
          convert -version

          ICON_PATH=${{ runner.temp }}/godot.ico
          convert -background transparent ${{ inputs.icon-path }} -define icon:auto-resize=256,128,64,48,32,16 $ICON_PATH
        fi

        cp $ICON_PATH ${{ github.workspace }}/godot/platform/windows/godot.ico

    # ---------------------- Compile the export template --------------------- #

    # MacOS

    # TODO: 'universal' builds cannot take advantage of 'x86_64'/'arm64'-
    # specific caches. Consider restructuring, but this is unlikely to be an
    # issue in practice because 'universal' is by far the most common arch.

    - name: Compile the export template (MacOS - x86_64)
      if: |
        inputs.platform == 'macos' &&
        (inputs.arch == 'x86_64' || inputs.arch == 'universal') &&
        steps.export-template.outputs.cache-hit != 'true'
      uses: "coffeebeats/godot-infra/compile-godot-export-template/macos@main"
      with:
        app-bundle: ${{ inputs.arch == 'x86_64' }}
        arch: x86_64
        encryption-key: ${{ inputs.encryption-key }}
        godot-src-path: godot
        profile: ${{ inputs.profile }}
        use-double-precision: ${{ inputs.use-double-precision }}

    - name: Compile the export template (MacOS - arm64+universal)
      if: |
        inputs.platform == 'macos'  &&
        (inputs.arch == 'arm64' || inputs.arch == 'universal') &&
        steps.export-template.outputs.cache-hit != 'true'
      uses: "coffeebeats/godot-infra/compile-godot-export-template/macos@main"
      with:
        app-bundle: true
        arch: arm64
        encryption-key: ${{ inputs.encryption-key }}
        godot-src-path: godot
        lipo: ${{ inputs.arch == 'universal' }}
        profile: ${{ inputs.profile }}
        use-double-precision: ${{ inputs.use-double-precision }}

    # Web

    - name: Compile the export template (Web - wasm32)
      if: |
        inputs.platform == 'web' &&
        steps.export-template.outputs.cache-hit != 'true'
      uses: "coffeebeats/godot-infra/compile-godot-export-template/web@main"
      with:
        arch: ${{ inputs.arch }}
        enable-gdextension: ${{ inputs.enable-gdextension }}
        enable-javascript-eval: ${{ inputs.enable-javascript-eval }}
        encryption-key: ${{ inputs.encryption-key }}
        godot-src-path: godot
        profile: ${{ inputs.profile }}
        use-double-precision: ${{ inputs.use-double-precision }}

    # Windows

    - name: Compile the export template (Windows - x86_64)
      if: |
        inputs.platform == 'windows' &&
        steps.export-template.outputs.cache-hit != 'true'
      uses: "coffeebeats/godot-infra/compile-godot-export-template/windows@main"
      with:
        arch: ${{ inputs.arch }}
        encryption-key: ${{ inputs.encryption-key }}
        godot-src-path: godot
        profile: ${{ inputs.profile }}
        use-double-precision: ${{ inputs.use-double-precision }}

    # ---------------------- Inspect compiled artifacts ---------------------- #

    - name: Move compiled artifacts
      if: steps.export-template.outputs.cache-hit != 'true'
      shell: bash
      run: |-
        if [[ -d "$GITHUB_WORKSPACE/build" ]]; then
          echo "Unexpectedly found output directory: $GITHUB_WORKSPACE/build"
          exit 1
        fi

        sudo mv $GITHUB_WORKSPACE/godot/bin $GITHUB_WORKSPACE/build

    - name: Inspect compiled artifacts
      shell: bash
      run: tree -lha --dirsfirst $GITHUB_WORKSPACE/build

    - name: Clean up Godot source code
      shell: bash
      run: sudo rm -rf $GITHUB_WORKSPACE/godot

    - name: Determine export template file name
      id: artifact
      shell: bash
      run: |
        case "${{ inputs.platform }}" in
          macos) TEMPLATE_NAME=macos.zip ;;
          web)
            PROFILE=$([[ "${{ inputs.profile }}" == release ]] && echo release || echo debug)
            DLINK=$([[ "${{ inputs.enable-gdextension }}" == true ]] && echo _dlink || :)

            TEMPLATE_NAME="web${DLINK}_${PROFILE}.zip"
            ;;
          windows)
            TARGET=$([[ "${{ inputs.profile }}" == release ]] && echo template_release || echo template_debug)
            DOUBLE=$([[ "${{ inputs.use-double-precision }}" == true ]] && echo ".double" || :)

            TEMPLATE_NAME="godot.${{ inputs.platform }}.${TARGET}${DOUBLE}.${{ inputs.arch }}"

            if [[ "${{ inputs.platform }}" == windows ]]; then
              TEMPLATE_NAME="${TEMPLATE_NAME}.exe"
            fi

            ;;
          *)
            echo "Unknown/unsupported platform: ${{ inputs.platform }}"
            exit 1
        esac

        echo "name=$([[ -z "${{ inputs.artifact-name }}" ]] && echo $TEMPLATE_NAME || echo ${{ inputs.artifact-name }})" >> $GITHUB_OUTPUT
        echo "path=$GITHUB_WORKSPACE/build/$TEMPLATE_NAME" >> $GITHUB_OUTPUT

    # ---------------------- Publish generated artifacts --------------------- #

    # Save the export template cache (ahead of post- step)
    - uses: actions/cache/save@v3
      if: steps.export-template.outputs.cache-hit != 'true'
      with:
        # IF/ELSE: Update the 'cache' step above if this changes.
        path: ${{ github.workspace }}/build
        key: export-template-${{ runner.os }}-${{ steps.export-template-cache-id.outputs.value }}

    # Compiled export template
    - uses: actions/upload-artifact@v4
      if: inputs.publish == 'true'
      with:
        name: ${{ steps.artifact.outputs.name }}
        path: ${{ steps.artifact.outputs.path }}
        if-no-files-found: error
