name: "ðŸ—ï¸ Compile: Godot export template (Windows)"
description: "Compiles a Godot export template for the Windows platform."

inputs:
  arch:
    description: "The target architecture to build the export template for."
    required: false
    default: x86_64
  target:
    description: "Which Godot build target to compile (e.g. 'editor' or 'template_debug')."
    required: true
  encryption-key:
    description: "A Godot script encryption key to embed within the export template."
    required: false
  use-double-precision:
    description: "Whether to enable double precision for the export template."
    required: false
    default: false
  profile:
    description: "The optimization profile of the compiled export template."
    required: false
    default: release
  godot-src-path:
    description: "A path, relative to 'github.workspace', where the Godot source code is located."
    required: false
    default: "."
  scons-cache-path:
    description: "A path, relative to 'github.workspace', where the SCons cache is located."
    required: false
    default: ".scons"

runs:
  using: docker
  image: docker://ghcr.io/coffeebeats/compile-godot-export-template:godot-v4.4-windows
  args:
    - /bin/bash
    - -c
    - >-
      if [[ ! -z "${{ inputs.encryption-key }}" ]]; then
      SCRIPT_AES256_ENCRYPTION_KEY=${{ inputs.encryption-key }};
      fi

      scons
      -j$(nproc)
      -C ${{ inputs.godot-src-path }}
      cache_path=/github/workspace/${{ inputs.scons-cache-path }}
      verbose=yes warnings=extra werror=yes
      arch=${{ inputs.arch }}
      target=${{ inputs.target }}
      $([[ "${{ inputs.target }}" == "editor" ]] && echo agility_sdk_path=)
      $([[ "${{ inputs.use-double-precision }}" == 'true' ]] && echo "precision=double")
      $([[ "${{ inputs.profile }}" == "debug" ]] && echo debug_symbols=yes optimize=debug)
      $([[ "${{ inputs.profile }}" == "release_debug" ]] && echo production=yes debug_symbols=yes optimize=speed_trace)
      $([[ "${{ inputs.profile }}" == "release" ]] && echo production=yes optimize=speed)
      $([[ "${{ inputs.profile }}" != "release" ]] && echo pix_path=/opt/pix)
