name: "🤖 godot-infra: Export 'gdbuild' target"

on:
  workflow_call:
    inputs:
      target:
        type: string
        description: "The name of the 'gdbuild' target to export."
        required: true
      platform:
        type: string
        description: "The platform to build the export template for."
        required: true
      profile:
        type: string
        description: "The profile to build the export template with."
        required: false
        default: release
      features:
        type: string
        description: "A space-, comma- or new line-separated list of features to enable."
        required: false
        default: ""
      project-dir:
        type: string
        description: "The path to the project directory."
        required: false
        default: example
      manifest-path:
        type: string
        description: "A specific 'gdbuild' manifest filepath (relative to 'project-dir')."
        required: false
      publish:
        type: boolean
        description: "Whether to publish an artifact to the workflow."
        required: false
        default: true
      os:
        type: string
        description: "The runner's operating system."
        required: false
        default: ubuntu-latest
      timeout:
        type: number
        description: "The workflow's maximum allowed run duration (in minutes)."
        required: false
        default: 60
    outputs:
      path:
        description: "The name of the 'godot' export template artifact."
        value: ${{ jobs.export.outputs.name }}
  workflow_dispatch:
    inputs:
      target:
        type: string
        description: "The name of the 'gdbuild' target to export."
        required: true
      platform:
        type: choice
        description: "The platform to build the export template for."
        required: true
        options:
          - "windows"
          - "macos"
      profile:
        type: string
        description: "The profile to build the export template with."
        required: false
        default: release
      features:
        type: string
        description: "A space-, comma- or new line-separated list of features to enable."
        required: false
        default: ""
      project-dir:
        type: string
        description: "The path to the project directory."
        required: false
        default: example
      manifest-path:
        type: string
        description: "A specific 'gdbuild' manifest filepath (relative to 'project-dir')."
        required: false
      publish:
        type: boolean
        description: "Whether to publish an artifact to the workflow."
        required: false
        default: true
      os:
        type: string
        description: "The runner's operating system."
        required: false
        default: ubuntu-latest
      timeout:
        type: number
        description: "The workflow's maximum allowed run duration (in minutes)."
        required: false
        default: 60

jobs:
  build:
    uses: "./.github/workflows/build-godot-template.yaml"
    secrets: "inherit"
    with:
      platform: ${{ inputs.platform }}
      profile: ${{ inputs.profile }}
      features: ${{ inputs.features }}
      project-dir: ${{ inputs.project-dir }}
      manifest-path: ${{ inputs.manifest-path }}
      publish: true
      os: ${{ inputs.os }}
      timeout: ${{ fromJson(inputs.timeout) }}

  export:
    needs: ["build"]

    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ fromJson(inputs.timeout) }}

    outputs:
      name: ${{ steps.config-artifact.outputs.name }}

    env:
      SCRIPT_AES256_ENCRYPTION_KEY: ${{ secrets.SCRIPT_AES256_ENCRYPTION_KEY }}

    steps:
      - uses: actions/checkout@v4

      # ------------------------ Install @coffeebeats tools ------------------------ #

      - name: Install 'gdenv'
        uses: coffeebeats/gdenv/.github/actions/setup-gdenv@main
        with:
          project-dir: ${{ inputs.project-dir }}

      - name: Install 'gdbuild'
        uses: coffeebeats/gdbuild/.github/actions/setup-gdbuild@main
        with:
          project-dir: ${{ inputs.project-dir }}

      # ----------------------------- Export the target ---------------------------- #

      # Download and extract export template.
      - name: Download 'godot' export template
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.path }}
          path: ${{ runner.temp }}
          merge-multiple: true

      - name: Export the target
        uses: ./.github/actions/export-gdbuild-target
        id: export-target
        with:
          target: ${{ inputs.target }}
          platform: ${{ inputs.platform }}
          profile: ${{ inputs.profile }}
          features: ${{ inputs.features }}
          project-dir: ${{ inputs.project-dir }}
          manifest-path: ${{ inputs.manifest-path }}
          template-archive-path: ${{ runner.temp }}/${{ needs.build.outputs.path }}

      # ------------------------ Package the export artifacts ---------------------- #

      - name: Configure the artifact name
        id: config-artifact
        shell: bash
        run: echo "name=${{ inputs.target }}-${{ inputs.platform }}-${{ inputs.profile }}" >> $GITHUB_OUTPUT

      # Publish the artifact
      - uses: actions/upload-artifact@v4
        if: fromJson(format('{0}', inputs.publish))
        with:
          name: ${{ steps.config-artifact.outputs.name }}
          path: ${{ steps.export-target.outputs.path }}
          retention-days: 7
          if-no-files-found: error
