name: "🧪 godot-infra: Placeholder workflow for testing"

on:
  workflow_dispatch:
    inputs:
      timeout:
        type: number
        description: "The workflow's maximum allowed run duration (in minutes)."
        required: false
        default: 60

jobs:
  compile:
    uses: "./.github/workflows/compile-godot-export-template.yaml"
    with:
      godot-src-rev: 4.2.2-stable
      godot-src-repository: godotengine/godot

      arch: x86_64
      platform: windows
      encryption-key: aeb1bc56aaf580cc31784e9c41551e9ed976ecba10d315db591e749f3f64890f
      custompy-path: ./example/custom.py
      use-double-precision: false
      profile: release

      # Windows-specific inputs.
      icon-path: ./example/icon.svg

  export:
    needs: ["compile"]

    uses: "./.github/workflows/export-godot-project-preset.yaml"
    with:
      project-path: ./example

      preset-name: "Windows Desktop"
      preset-output-name: "game.exe"
      pck-only: false

      godot-editor-version: 4.2.2-stable
      export-template-artifact-name: ${{ needs.compile.outputs.name }}

      profile: release
      encryption-key: aeb1bc56aaf580cc31784e9c41551e9ed976ecba10d315db591e749f3f64890f
