name: "🧪 godot-infra: Placeholder workflow for testing"

on:
  workflow_dispatch:
    inputs:
      platform:
        type: string
        description: "The platform to build the export template for."
        required: false
        default: windows
      os:
        type: string
        description: "The runner's operating system."
        required: false
        default: ubuntu-latest
      timeout:
        type: number
        description: "The workflow's maximum allowed run duration (in minutes)."
        required: false
        default: 60

jobs:
  todo:
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ fromJson(inputs.timeout) }}

    steps:
      - uses: actions/checkout@v4

      # ------------------------ Install @coffeebeats tools ------------------------ #

      - name: Install 'gdenv'
        uses: coffeebeats/gdenv/.github/actions/setup-gdenv@main
        with:
          # NOTE: The editor and source code must be pre-installed, otherwise 'gdenv'
          # will fail moving the downloaded artifact into the mounted volume.
          project-dir: ./example
          install-src: true

      - name: Install 'gdbuild'
        uses: coffeebeats/gdbuild/.github/actions/setup-gdbuild@main

      # ------------------------ Compile the export template ----------------------- #

      - name: Set up 'podman'
        uses: ./.github/actions/setup-podman
        with:
          install-buildah: true
          install-podman: false
          login: true

      - name: Compile the export template
        uses: ./.github/actions/build-godot-template
        id: build-template
        with:
          platform: windows
          project-dir: ./example

      # ---------------------------- Inspect the results --------------------------- #

      - name: Inspect the results
        shell: bash
        run: ls ${{ steps.build-template.outputs.directory }}
