name: "🧪 godot-infra: Placeholder workflow for testing"

on:
  workflow_dispatch:
    inputs:
      os:
        type: string
        description: "The runner's operating system."
        required: false
        default: ubuntu-latest
      timeout:
        type: number
        description: "The workflow's maximum allowed run duration (in minutes)."
        required: false
        default: 60

jobs:
  todo:
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ fromJson(inputs.timeout) }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./compile-godot-export-template
        with:
          platform: windows
          godot-version: 4.2.2-stable
          encryption-key: aeb1bc56aaf580cc31784e9c41551e9ed976ecba10d315db591e749f3f64890f
          custompy-path: example/custom.py
          use-double-precision:
          profile: release
          icon-path: example/icon.svg
