name: "🧪 godot-infra: Placeholder workflow for testing"

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        required: false
        default: windows
        options:
          - windows
          - macos
      arch:
        type: choice
        required: false
        default: x86_64
        options:
          - x86_64
          - arm64
          - universal
      profile:
        type: choice
        required: false
        default: debug
        options:
          - debug
          - release_debug
          - release
      godot-src-rev:
        type: string
        required: false
        default: 4.2.1-stable
      godot-src-repository:
        type: string
        required: false
        default: godotengine/godot
      preset:
        type: choice
        required: false
        default: "Windows Desktop"
        options:
          - "Windows Desktop"
          - "macOS"
      timeout:
        type: number
        description: "The workflow's maximum allowed run duration (in minutes)."
        required: false
        default: 60

jobs:
  compile:
    uses: "./.github/workflows/compile-godot-export-template.yaml"
    with:
      godot-src-rev: ${{ inputs.godot-src-rev }}
      godot-src-repository: ${{ inputs.godot-src-repository }}

      arch: ${{ inputs.arch }}
      platform: ${{ inputs.platform }}
      encryption-key: ${{ secrets.SCRIPT_AES256_ENCRYPTION_KEY }}
      custompy-path: ./example/custom.py
      use-double-precision: false
      profile: ${{ inputs.profile }}

      # Windows-specific inputs.
      icon-path: ./example/icon.svg

  export:
    needs: ["compile"]

    uses: "./.github/workflows/export-godot-project-preset.yaml"
    with:
      project-path: ./example

      preset-name: ${{ inputs.preset }}
      preset-output-name: "game.exe"
      pck-only: false

      godot-editor-version: ${{ inputs.godot-src-rev }}
      export-template-artifact-name: ${{ needs.compile.outputs.name }}

      profile: ${{ inputs.profile }}
      encryption-key: ${{ secrets.SCRIPT_AES256_ENCRYPTION_KEY }}
